spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true #重试机制开启 ribbon专用
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
user-service:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
logging:
  level:
    com.xia.demo.*: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms
