spring:
  application:
    name: eureka-server
server:
  port: 10086
eureka:
  client:
    fetch-registry: false #是否拉取其它服务的信息，默认是true 如果是eureka集群默认就可以了
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka